services:
  fastapi-server:
    build:
      context: ../fastapi
      dockerfile: Dockerfile
    container_name: fastapi_superres
    ports:
      - "5000:5000"
    volumes:
      - ../fastapi:/app
      - /mnt/block:/mnt/block
    command: uvicorn main:app --host 0.0.0.0 --port 5000