version: "3.8"

volumes:
  sr:

services:
  extract-data:
    container_name: etl_extract_data
    image: python:3.11
    user: root
    volumes:
      - sr:/data
    working_dir: /data
    command: >
      bash -c "set -e
               # download & unpack HR
               for f in DIV2K_train_HR DIV2K_valid_HR; do
                 url=https://data.vision.ee.ethz.ch/cvl/DIV2K/$$f.zip
                 curl -L \"$$url\" -o $$f.zip
                 unzip -q $$f.zip && rm $$f.zip
               done

               # download & unpack LR ×4
               for f in DIV2K_train_LR_bicubic_X4 DIV2K_valid_LR_bicubic_X4; do
                 url=https://data.vision.ee.ethz.ch/cvl/DIV2K/$$f.zip
                 curl -L \"$$url\" -o $$f.zip
                 unzip -q $$f.zip && rm $$f.zip
               done

               echo '>>> /data now contains:' 
               ls -lhR /data
      "

  transform-data:
    container_name: etl_transform_data
    image: python:3.11
    user: root
    volumes:
      - sr:/data
    working_dir: /data
    command: >
      bash -lc "
        set -eux

        mkdir -p SR/div2k/{train,validation,lr,hr}

        # move HR
        mv DIV2K_train_HR/*     SR/div2k/train/
        mv DIV2K_valid_HR/*     SR/div2k/validation/

        # move LR ×4
        mv DIV2K_train_LR_bicubic/X4/*  SR/div2k/lr/
        mv DIV2K_valid_LR_bicubic/X4/*  SR/div2k/hr/

        echo '>>> SR/div2k:'
        ls -lhR SR/div2k
      "

  load-data:
    container_name: etl_load_data
    image: rclone/rclone:latest
    volumes:
      - sr:/data
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
    entrypoint: /bin/sh
    command: |
      set -e
      rclone delete chi_tacc:$RCLONE_CONTAINER --rmdirs || true
      rclone copy /data/SR chi_tacc:$RCLONE_CONTAINER --progress
      rclone lsd chi_tacc:$RCLONE_CONTAINER