version: "3.8"

volumes:
  sr:

services:
  extract-data:
    container_name: etl_extract_data
    image: python:3.11
    user: root
    volumes:
      - sr:/data
    working_dir: /data
    command: >
      bash -c "set -e
               # download & unpack HR
               for f in DIV2K_train_HR DIV2K_valid_HR; do
                 url=https://data.vision.ee.ethz.ch/cvl/DIV2K/$$f.zip
                 curl -L \"$$url\" -o $$f.zip
                 unzip -q $$f.zip && rm $$f.zip
               done

               # download & unpack LR ×4
               for f in DIV2K_train_LR_bicubic_X4 DIV2K_valid_LR_bicubic_X4; do
                 url=https://data.vision.ee.ethz.ch/cvl/DIV2K/$$f.zip
                 curl -L \"$$url\" -o $$f.zip
                 unzip -q $$f.zip && rm $$f.zip
               done

               echo '>>> /data now contains:' 
               ls -lhR /data
      "

  transform-data:
    container_name: etl_transform_data
    image: python:3.11
    user: root
    volumes:
      - sr:/data
    working_dir: /data
    command: >
      bash -c "set -e

        # 1) Make the target dirs
        mkdir -p SR/div2k/{train,validation,lr,hr}

        # 2) Move the 800 training HR images (0001–0800)
        for i in {0001..0800}; do
          mv \"\$i.png\" SR/div2k/train/
        done

        # 3) Move the 100 validation HR images
        mv DIV2K_valid_HR/* SR/div2k/validation/
        rmdir DIV2K_valid_HR

        # 4) Move the LR ×4 images
        mv DIV2K_train_LR_bicubic/X4/* SR/div2k/lr/
        rm -r DIV2K_train_LR_bicubic

        mv DIV2K_valid_LR_bicubic/X4/* SR/div2k/hr/
        rm -r DIV2K_valid_LR_bicubic

        # 5) Verify
        echo '>>> Final SR/div2k layout:'
        ls -lhR SR/div2k
      "

  load-data:
    container_name: etl_load_data
    image: rclone/rclone:latest
    volumes:
      - sr:/data
      - ~/.config/rclone/rclone.conf:/root/.config/rclone/rclone.conf:ro
    entrypoint: /bin/sh
    command: |
      set -e
      rclone delete chi_tacc:$RCLONE_CONTAINER --rmdirs || true
      rclone copy /data/SR chi_tacc:$RCLONE_CONTAINER --progress
      rclone lsd chi_tacc:$RCLONE_CONTAINER