version: "3.8"

services:
  fastapi-server:
    build:
      context: ../fastapi
      dockerfile: Dockerfile
    container_name: fastapi_superres
    ports:
      - "8001:8001"
    volumes:
      - ../fastapi:/app
      - /mnt/block:/mnt/block
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload