services:
  fastapi-server:
    build:
      context: ./fastapi
    container_name: fastapi_superres
    ports:
      - "8001:8001"
    volumes:
      - ./fastapi:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped