global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'mlflow'
    static_configs:
      - targets: ['mlflow:8000']

  - job_name: 'jupyter'
    static_configs:
      - targets: ['jupyter:8888']